name: Run tests with Testcontainers

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker CE
        run: |
          sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build JAR
        run: ./gradlew bootJar

      - name: Build Docker image for Testcontainers
        run: docker build -t cdq.demo.vies .

      - name: Run tests
        run: ./gradlew test
        env:
          TESTCONTAINERS_CHECKS_DISABLE: true


      - name:  Dump container logs
        run: docker logs $(docker ps -q --filter ancestor=cdq.demo.vies) > container.log || echo "No logs"
        continue-on-error: true
